### ISSUE TITLE
Readme is confusing

### ISSUE THREAD

**Issue by JonathanMortes** [justinjohn0306/PF-AFN-Windows#1]
Hi, 
I'm trying to validate your work but I cannot get  it to work. I've got all the dependences correct but your folder path is very confusing and after several attempts I keep getting an error with No checkPoint and 

```
No checkpoint!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\ANACONDA\envs\tryon\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\ANACONDA\envs\tryon\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\ANACONDA\envs\tryon\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JONY-\checkpoints\PF-AFN\PF-AFN_test\test.py", line 40, in <module>
    for i, data in enumerate(dataset, start=epoch_iter):
  File "D:\ANACONDA\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\ANACONDA\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\ANACONDA\envs\tryon\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

(tryon) C:\Users\JME\checkpoints\PF-AFN\PF-AFN_test>
```

If you could more clearly detail the correct path for reproducing your results, it would be greatly appreciated. Furthermore, if you've encountered this issue and have any insight, please let me know.

Thanks,
Jonathan Mortes

**Comment by R4ZZ3** [comment]
Hi, I got the same error. I am also running the example in the same directory and have checkpoints placed under PF-AFN_test/checkpoints. Waithing for comment from authors

**Comment by JonathanMortes** [comment]
I made it work. Will try to do a commit in the following days

**Comment by R4ZZ3** [comment]
GJ, ping me once ready @JonathanMortes
